# Generated by Django 5.1 on 2024-09-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='estimateequipment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
