# Generated by Django 5.1 on 2024-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_alter_estimate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
