# Generated by Django 5.1 on 2024-09-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='flag',
            field=models.BooleanField(default=True, help_text='Whether it is active or not'),
        ),
    ]
